version: '3.7'
services:
  shorty:
    image: motherdock/java:SpringBootRunner
    container_name: SpringAppShorty
    ports:
      - "8081:8080"
    volumes:
      - /home/ubuntu/app/shorty:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - javaAppNet

networks:
  javaAppNet:
    external: true
